### ISSUE TITLE
[Required] Add a way to make transactions

### ISSUE THREAD

**Issue by ArgTang** [ArgTang/WebApplikasjonProject#64]
Add function to make transactions
When both accounts are within the same bank, make transaction happen.
When both accounts are for the same user make transaction at once

[optional] Batchjob - 3 times a day run all transactions that has data today.

**Comment by aleksanderaleksic** [comment]
Tider : 05.35, 11.05, 13.35 og 15.35.

**Comment by aleksanderaleksic** [comment]
#103

**Comment by oleespen** [comment]
#106
