### ISSUE TITLE
[Required] Controller logic into BLL

### ISSUE THREAD

**Issue by ArgTang** [ArgTang/WebApplikasjonProject#75]
Move Controller logic into a BLL layer

Controller methods should not have any logic, move these into a BLL class. (as per request by Tor)

**Comment by aleksanderaleksic** [comment]
Ole tar UserController
Alex tar BankID Controller når ole er ferdig

**Comment by oleespen** [comment]
får ikke til å legge alt til BLL. trenger hjelp til dette fra userController

**Comment by oleespen** [comment]
Sliter med å lage metoder for logikken i userController i userBLL.

**Comment by aleksanderaleksic** [comment]
BankidBLL ferdig

**Comment by aleksanderaleksic** [comment]
#102
